// <auto-generated />
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusiness.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20220401173131_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("GoodsType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Hours")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Website")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Address = "853 Leonor Points, HipolitoFurt, IL 83006",
                            GoodsType = "Apparel",
                            Hours = "9am to 5pm",
                            Name = "Matilda's Dresses",
                            PhoneNumber = 2278656128L,
                            Website = "matildasdresses.com"
                        },
                        new
                        {
                            BusinessId = 2,
                            Address = "949 Schroeder Meadow, Kirkland, WA 98052",
                            GoodsType = "Fossils",
                            Hours = "10am to 8pm",
                            Name = "Rexie's Fossils",
                            PhoneNumber = 5383392548L,
                            Website = "rexiesfossils.com"
                        },
                        new
                        {
                            BusinessId = 3,
                            Address = "64347 Jake Bypass, East Garretfort, TX 70158",
                            GoodsType = "Outdoor recreation",
                            Hours = "10am to 9pm",
                            Name = "Miranda's Outdoor Gear",
                            PhoneNumber = 7898901979L,
                            Website = "mirandasoutdoors.com"
                        },
                        new
                        {
                            BusinessId = 4,
                            Address = "2101 Hermina Plaza Suite 649, Braedenland, WA 86302",
                            GoodsType = "Tea",
                            Hours = "6am to 5pm",
                            Name = "Pip and Squeak",
                            PhoneNumber = 5034968358L,
                            Website = "pipandsqueaktea.com"
                        },
                        new
                        {
                            BusinessId = 5,
                            Address = "394 Alford Station, East Chanel, CT 64520",
                            GoodsType = "Books",
                            Hours = "9am to 9pm",
                            Name = "Bartholomew's Books",
                            PhoneNumber = 3086879381L,
                            Website = "bartsbooksandcomics.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
